# Generated by Django 6.0.6 on 2026-06-09 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ticketcomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='device_serial_number',
            field=models.CharField(blank=True, max_length=150, verbose_name='Device serial number'),
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/%d/')),
                ('description', models.CharField(blank=True, max_length=250)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.ticket')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ticket attachment',
                'verbose_name_plural': 'ticket attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
