# Generated by Django 6.0.6 on 2026-06-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ticket_device_serial_number_ticketattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='floor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ticket',
            name='room_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ticket',
            name='wing',
            field=models.CharField(blank=True, choices=[('EACJ', 'EACJ'), ('Secretariat', 'Secretariat'), ('EALA', 'EALA')], default='EACJ', max_length=20),
        ),
    ]
