# Generated by Django 6.0.6 on 2026-06-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ticket_floor_ticket_room_number_ticket_wing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='floor',
            field=models.CharField(blank=True, choices=[('ground', 'Ground Floor'), ('first', 'First Floor'), ('second', 'Second Floor'), ('third', 'Third Floor')], max_length=20),
        ),
    ]
