# Generated by Django 6.0.6 on 2026-06-09 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_ticket_floor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='location',
        ),
    ]
