# Generated by Django 6.0.6 on 2026-06-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_ticket_reopened_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='reopen_reason',
            field=models.TextField(blank=True),
        ),
    ]
