# Generated by Django 6.0.6 on 2026-06-09 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_ticket_reopen_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=150, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('wing', models.CharField(blank=True, choices=[('EACJ', 'EACJ'), ('Secretariat', 'Secretariat'), ('EALA', 'EALA')], default='EACJ', max_length=20)),
                ('floor', models.CharField(blank=True, choices=[('ground', 'Ground Floor'), ('first', 'First Floor'), ('second', 'Second Floor'), ('third', 'Third Floor')], max_length=20)),
                ('room_number', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('operational', 'Operational'), ('maintenance_due', 'Maintenance due'), ('decommissioned', 'Decommissioned')], default='operational', max_length=20)),
                ('condition', models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=20)),
                ('last_inspected', models.DateField(blank=True, null=True)),
                ('next_inspection', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'device',
                'verbose_name_plural': 'devices',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='core.device'),
        ),
    ]
