# Generated by Django 6.0.6 on 2026-06-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_ticket_device_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('monitor', 'Monitor'), ('ups', 'UPS'), ('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('cpu', 'CPU'), ('laptop', 'Laptop'), ('printer', 'Printer'), ('scanner', 'Scanner'), ('server', 'Server'), ('projector', 'Projector'), ('ip_phone', 'IP Phone'), ('tablet', 'Tablet'), ('conference', 'Conference System'), ('network', 'Network Device'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='device',
            name='other_device_type',
            field=models.CharField(blank=True, help_text="Specify the hardware type if 'Other' is selected.", max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.CharField(max_length=150),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('serial_number', 'device_type'), name='unique_serial_per_device_type'),
        ),
    ]
