# Generated by Django 6.0.6 on 2026-06-11 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_knowledgebasearticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='assigned_user',
            field=models.ForeignKey(blank=True, help_text='The staff member currently in possession of this device.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_devices', to=settings.AUTH_USER_MODEL),
        ),
    ]
