# Generated by Django 6.0.6 on 2026-06-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_device_assigned_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='due_at',
            field=models.DateTimeField(blank=True, help_text='SLA Deadline based on priority.', null=True),
        ),
    ]
