# Generated by Django 6.0.6 on 2026-06-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_ticket_due_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='technician_type',
            field=models.CharField(blank=True, choices=[('it', 'IT Support'), ('electrical', 'Electrical / Power'), ('plumbing', 'Plumbing'), ('mechanical', 'Mechanical / HVAC'), ('electronics', 'Electronics'), ('other', 'Other')], help_text='Specialization area for technician users.', max_length=50, null=True),
        ),
    ]
