# Generated by Django 6.0.6 on 2026-06-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_customuser_technician_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ai_suggested_category',
            field=models.CharField(blank=True, help_text='AI-suggested category based on description.', max_length=100, null=True),
        ),
    ]
