# Generated by Django 6.0.6 on 2026-06-12 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_material_alter_customuser_role_materialrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='material_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.materialrequest'),
        ),
    ]
