from django.urls import path

from .views import (
    AuditLogCSVView,
    AuditLogExcelView,
    AuditLogListView,
    AuditLogPDFView,
    DashboardView,
    RegisterView,
    TicketAttachmentCreateView,
    TicketCommentCreateView,
    TicketCreateView,
    TicketDetailView,
    TicketListView,
    TicketReportCSVView,
    TicketReportExcelView,
    TicketReportPDFView,
    TicketReportView,
    DeviceListView,
    DeviceCreateView,
    DeviceDetailView,
    DeviceUpdateView,
    DeviceAuditReportView,
    DeviceAuditReportCSVView,
    DeviceAuditReportExcelView,
    DeviceAuditReportPDFView,

    TicketResolveView,
    TicketCloseView,
    TicketReopenView,
    TicketUpdateView,
    TicketAssignView,
    SendOverdueTicketNotificationsView,
    SendStaleTicketNotificationsView,
    UserListView,
    UserLogoutView,
    UserLoginView,
    UserUpdateView,
    KnowledgeBaseListView,
    KnowledgeBaseDetailView,
    KnowledgeBaseCreateView,
    KnowledgeBaseUpdateView,
    MaterialRequestCreateView,
    MaterialRequestListView,
    MaterialRequestDetailView,
    MaterialRequestApproveView,
    MaterialRequestRejectView,
    MaterialRequestIssueView,
)

urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('tickets/', TicketListView.as_view(), name='ticket_list'),
    path('tickets/create/', TicketCreateView.as_view(), name='ticket_create'),
    path('tickets/<int:pk>/', TicketDetailView.as_view(), name='ticket_detail'),
    path('tickets/<int:pk>/comment/', TicketCommentCreateView.as_view(), name='ticket_comment'),
    path('tickets/<int:pk>/attach/', TicketAttachmentCreateView.as_view(), name='ticket_attachment'),
    path('tickets/<int:pk>/edit/', TicketUpdateView.as_view(), name='ticket_update'),
    path('tickets/<int:pk>/assign/', TicketAssignView.as_view(), name='ticket_assign'),
    path('tickets/<int:pk>/resolve/', TicketResolveView.as_view(), name='ticket_resolve'),
    path('tickets/<int:pk>/close/', TicketCloseView.as_view(), name='ticket_close'),
    path('tickets/<int:pk>/reopen/', TicketReopenView.as_view(), name='ticket_reopen'),
    path('tickets/report/', TicketReportView.as_view(), name='ticket_report'),
    path('tickets/report/pdf/', TicketReportPDFView.as_view(), name='ticket_report_pdf'),
    path('tickets/report/excel/', TicketReportExcelView.as_view(), name='ticket_report_excel'),
    path('tickets/report/csv/', TicketReportCSVView.as_view(), name='ticket_report_csv'),
    path('tickets/stale-notifications/send/', SendStaleTicketNotificationsView.as_view(), name='stale_notification_send'),
    path('tickets/overdue-notifications/send/', SendOverdueTicketNotificationsView.as_view(), name='overdue_notification_send'),
    path('users/', UserListView.as_view(), name='user_list'),
    path('users/<int:pk>/edit/', UserUpdateView.as_view(), name='user_edit'),
    path('audit-logs/', AuditLogListView.as_view(), name='audit_log_list'),
    path('audit-logs/report/pdf/', AuditLogPDFView.as_view(), name='audit_report_pdf'),
    path('audit-logs/report/excel/', AuditLogExcelView.as_view(), name='audit_report_excel'),
    path('audit-logs/report/csv/', AuditLogCSVView.as_view(), name='audit_report_csv'),
    path('devices/', DeviceListView.as_view(), name='device_list'),
    path('devices/create/', DeviceCreateView.as_view(), name='device_create'),
    path('devices/<int:pk>/', DeviceDetailView.as_view(), name='device_detail'),
    path('devices/<int:pk>/edit/', DeviceUpdateView.as_view(), name='device_edit'),
    path('devices/audit/', DeviceAuditReportView.as_view(), name='device_audit_report'),
    path('devices/audit/pdf/', DeviceAuditReportPDFView.as_view(), name='device_audit_report_pdf'),
    path('devices/audit/excel/', DeviceAuditReportExcelView.as_view(), name='device_audit_report_excel'),
    path('devices/audit/csv/', DeviceAuditReportCSVView.as_view(), name='device_audit_report_csv'),
    path('kb/', KnowledgeBaseListView.as_view(), name='kb_list'),
    path('kb/create/', KnowledgeBaseCreateView.as_view(), name='kb_create'),
    path('kb/<int:pk>/', KnowledgeBaseDetailView.as_view(), name='kb_detail'),
    path('kb/<int:pk>/edit/', KnowledgeBaseUpdateView.as_view(), name='kb_edit'),
    path('material-requests/', MaterialRequestListView.as_view(), name='material_request_list'),
    path('material-requests/create/', MaterialRequestCreateView.as_view(), name='material_request_create'),
    path('material-requests/<int:pk>/', MaterialRequestDetailView.as_view(), name='material_request_detail'),
    path('material-requests/<int:pk>/approve/', MaterialRequestApproveView.as_view(), name='material_request_approve'),
    path('material-requests/<int:pk>/reject/', MaterialRequestRejectView.as_view(), name='material_request_reject'),
    path('material-requests/<int:pk>/issue/', MaterialRequestIssueView.as_view(), name='material_request_issue'),
]
